# Generated by Django 4.0.2 on 2022-03-23 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigencia', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.categoria')),
                ('persona_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivos', models.FileField(blank=True, null=True, upload_to='archivos_subidos')),
                ('descripcion_archivos', models.TextField(blank=True, null=True)),
                ('links_relevantes', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comentario', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comentarios', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comentarios', to='cursos.modulos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
