# Generated by Django 2.2.12 on 2022-01-15 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos', models.FileField(max_length=20, null=True, upload_to='archivos_subidos')),
                ('fecha_de_creación', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=20, null=True, upload_to='videos')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField(null=True)),
                ('modulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video', to='cursos.Modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercitación',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplo', models.TextField(null=True)),
                ('modulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ejercitación', to='cursos.Modulos')),
            ],
        ),
    ]
