<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-07 23:32

from django.conf import settings
=======
# Generated by Django 4.0 on 2022-02-03 19:50

>>>>>>> d5bdc99697822058f3de74613d15717436643c88
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> d5bdc99697822058f3de74613d15717436643c88
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creación', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_publicación', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo_curso', models.CharField(max_length=50)),
                ('descripcion_curso', models.TextField()),
                ('vigencia', models.DateTimeField(default=django.utils.timezone.now)),
<<<<<<< HEAD
                ('persona_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
=======
                ('persona_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='auth.user')),
>>>>>>> d5bdc99697822058f3de74613d15717436643c88
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modulos',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='fecha_de_creación',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='fecha_de_publicación',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='modulos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.modulos'),
        ),
        migrations.DeleteModel(
            name='Ejercitación',
        ),
        migrations.AddField(
            model_name='modulos',
            name='cursos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso'),
            preserve_default=False,
        ),
    ]
