# Generated by Django 4.0.2 on 2022-02-09 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0003_alter_curso_persona_asignada_alter_modulos_archivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
