# Generated by Django 4.0.2 on 2022-02-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descripcion_curso',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='titulo_curso',
            new_name='titulo',
        ),
    ]
