# Generated by Django 4.0.2 on 2022-02-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_descripcion_curso_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulos',
            old_name='cursos',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='modulos',
            new_name='modulo',
        ),
    ]
