# Generated by Django 4.0.2 on 2022-02-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_rename_cursos_modulos_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='modulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulos'),
        ),
    ]
