# Generated by Django 4.0.2 on 2022-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_categoria_alter_curso_id_alter_modulos_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='descripcion_archivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='links_relevantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
