# Generated by Django 4.0.2 on 2022-02-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_modulos_descripcion_modulos_descripcion_archivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_de_creación',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_de_creación',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='fecha_de_creación',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
