# Generated by Django 4.0 on 2022-01-14 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('formacion_academica', models.TextField(max_length=500)),
                ('profesion', models.TextField(max_length=100)),
                ('fotos', models.ImageField(null=True, upload_to='fotos')),
                ('webPage', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=500)),
                ('nacimiento', models.DateField(default=django.utils.timezone.now, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
