# Generated by Django 4.0 on 2022-01-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='formacion_academica',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='profesion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='webPage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='youtube',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
