# Generated by Django 4.0 on 2022-02-02 01:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('perfiles', '0002_remove_perfiles_apellidos_remove_perfiles_biografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='author',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
