# Generated by Django 4.0 on 2022-02-03 19:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_remove_perfiles_author_perfiles_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='generos',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='formacion_academica',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='profesion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='webPage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
