# Generated by Django 4.0 on 2022-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_perfiles_generos_alter_perfiles_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='ingles',
            field=models.CharField(blank=True, choices=[('Nulo', 'Nulo'), ('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Nulo', max_length=12, null=True),
        ),
    ]
