# Generated by Django 4.0 on 2022-02-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_perfiles_ingles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='generos',
            new_name='genero',
        ),
    ]
