# Generated by Django 4.0 on 2022-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_rename_generos_perfiles_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='facebook',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='linkedin',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='twitter',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='webPage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='youtube',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
