# Generated by Django 4.0 on 2022-02-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_alter_perfiles_facebook_alter_perfiles_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
