# Generated by Django 4.0 on 2022-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_alter_perfiles_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='webPage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
