# Generated by Django 4.0 on 2022-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_alter_perfiles_linkedin_alter_perfiles_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='ingles',
            field=models.CharField(choices=[('Nulo', 'Nulo'), ('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Nulo', max_length=12),
        ),
    ]
