# Generated by Django 4.0 on 2022-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0010_alter_perfiles_ingles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='ingles',
            field=models.CharField(blank=True, choices=[('Nulo', 'Nulo'), ('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Nulo', max_length=12, null=True),
        ),
    ]
